version: '3.8'

services:
  bycf:
    build: .
    container_name: wesker bycf
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000     # port
      - AUTH_KEY=     # isi kalau mau pakai auth key
    shm_size: '256mb'
    cap_add:
      - SYS_ADMIN     # untuk Puppeteer di Docker
      
